# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhangsy/20210127/msisensor-ct/vendor/xgboost

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhangsy/20210127/msisensor-ct

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangsy/20210127/msisensor-ct/CMakeFiles /home/zhangsy/20210127/msisensor-ct/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangsy/20210127/msisensor-ct/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rabit

# Build rule for target.
rabit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rabit
.PHONY : rabit

# fast build rule for target.
rabit/fast:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/build
.PHONY : rabit/fast

#=============================================================================
# Target rules for targets named objxgboost

# Build rule for target.
objxgboost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objxgboost
.PHONY : objxgboost

# fast build rule for target.
objxgboost/fast:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/build
.PHONY : objxgboost/fast

#=============================================================================
# Target rules for targets named xgboost

# Build rule for target.
xgboost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xgboost
.PHONY : xgboost

# fast build rule for target.
xgboost/fast:
	$(MAKE) -f CMakeFiles/xgboost.dir/build.make CMakeFiles/xgboost.dir/build
.PHONY : xgboost/fast

#=============================================================================
# Target rules for targets named runxgboost

# Build rule for target.
runxgboost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runxgboost
.PHONY : runxgboost

# fast build rule for target.
runxgboost/fast:
	$(MAKE) -f CMakeFiles/runxgboost.dir/build.make CMakeFiles/runxgboost.dir/build
.PHONY : runxgboost/fast

#=============================================================================
# Target rules for targets named dmlc

# Build rule for target.
dmlc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dmlc
.PHONY : dmlc

# fast build rule for target.
dmlc/fast:
	$(MAKE) -f dmlc-core/CMakeFiles/dmlc.dir/build.make dmlc-core/CMakeFiles/dmlc.dir/build
.PHONY : dmlc/fast

#=============================================================================
# Target rules for targets named dmlc_lint

# Build rule for target.
dmlc_lint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dmlc_lint
.PHONY : dmlc_lint

# fast build rule for target.
dmlc_lint/fast:
	$(MAKE) -f dmlc-core/CMakeFiles/dmlc_lint.dir/build.make dmlc-core/CMakeFiles/dmlc_lint.dir/build
.PHONY : dmlc_lint/fast

rabit/src/allreduce_base.o: rabit/src/allreduce_base.cc.o

.PHONY : rabit/src/allreduce_base.o

# target to build an object file
rabit/src/allreduce_base.cc.o:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
.PHONY : rabit/src/allreduce_base.cc.o

rabit/src/allreduce_base.i: rabit/src/allreduce_base.cc.i

.PHONY : rabit/src/allreduce_base.i

# target to preprocess a source file
rabit/src/allreduce_base.cc.i:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.i
.PHONY : rabit/src/allreduce_base.cc.i

rabit/src/allreduce_base.s: rabit/src/allreduce_base.cc.s

.PHONY : rabit/src/allreduce_base.s

# target to generate assembly for a file
rabit/src/allreduce_base.cc.s:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.s
.PHONY : rabit/src/allreduce_base.cc.s

rabit/src/allreduce_robust.o: rabit/src/allreduce_robust.cc.o

.PHONY : rabit/src/allreduce_robust.o

# target to build an object file
rabit/src/allreduce_robust.cc.o:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.o
.PHONY : rabit/src/allreduce_robust.cc.o

rabit/src/allreduce_robust.i: rabit/src/allreduce_robust.cc.i

.PHONY : rabit/src/allreduce_robust.i

# target to preprocess a source file
rabit/src/allreduce_robust.cc.i:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.i
.PHONY : rabit/src/allreduce_robust.cc.i

rabit/src/allreduce_robust.s: rabit/src/allreduce_robust.cc.s

.PHONY : rabit/src/allreduce_robust.s

# target to generate assembly for a file
rabit/src/allreduce_robust.cc.s:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.s
.PHONY : rabit/src/allreduce_robust.cc.s

rabit/src/c_api.o: rabit/src/c_api.cc.o

.PHONY : rabit/src/c_api.o

# target to build an object file
rabit/src/c_api.cc.o:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/c_api.cc.o
.PHONY : rabit/src/c_api.cc.o

rabit/src/c_api.i: rabit/src/c_api.cc.i

.PHONY : rabit/src/c_api.i

# target to preprocess a source file
rabit/src/c_api.cc.i:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/c_api.cc.i
.PHONY : rabit/src/c_api.cc.i

rabit/src/c_api.s: rabit/src/c_api.cc.s

.PHONY : rabit/src/c_api.s

# target to generate assembly for a file
rabit/src/c_api.cc.s:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/c_api.cc.s
.PHONY : rabit/src/c_api.cc.s

rabit/src/engine.o: rabit/src/engine.cc.o

.PHONY : rabit/src/engine.o

# target to build an object file
rabit/src/engine.cc.o:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/engine.cc.o
.PHONY : rabit/src/engine.cc.o

rabit/src/engine.i: rabit/src/engine.cc.i

.PHONY : rabit/src/engine.i

# target to preprocess a source file
rabit/src/engine.cc.i:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/engine.cc.i
.PHONY : rabit/src/engine.cc.i

rabit/src/engine.s: rabit/src/engine.cc.s

.PHONY : rabit/src/engine.s

# target to generate assembly for a file
rabit/src/engine.cc.s:
	$(MAKE) -f CMakeFiles/rabit.dir/build.make CMakeFiles/rabit.dir/rabit/src/engine.cc.s
.PHONY : rabit/src/engine.cc.s

src/c_api/c_api.o: src/c_api/c_api.cc.o

.PHONY : src/c_api/c_api.o

# target to build an object file
src/c_api/c_api.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/c_api/c_api.cc.o
.PHONY : src/c_api/c_api.cc.o

src/c_api/c_api.i: src/c_api/c_api.cc.i

.PHONY : src/c_api/c_api.i

# target to preprocess a source file
src/c_api/c_api.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/c_api/c_api.cc.i
.PHONY : src/c_api/c_api.cc.i

src/c_api/c_api.s: src/c_api/c_api.cc.s

.PHONY : src/c_api/c_api.s

# target to generate assembly for a file
src/c_api/c_api.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/c_api/c_api.cc.s
.PHONY : src/c_api/c_api.cc.s

src/c_api/c_api_error.o: src/c_api/c_api_error.cc.o

.PHONY : src/c_api/c_api_error.o

# target to build an object file
src/c_api/c_api_error.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/c_api/c_api_error.cc.o
.PHONY : src/c_api/c_api_error.cc.o

src/c_api/c_api_error.i: src/c_api/c_api_error.cc.i

.PHONY : src/c_api/c_api_error.i

# target to preprocess a source file
src/c_api/c_api_error.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/c_api/c_api_error.cc.i
.PHONY : src/c_api/c_api_error.cc.i

src/c_api/c_api_error.s: src/c_api/c_api_error.cc.s

.PHONY : src/c_api/c_api_error.s

# target to generate assembly for a file
src/c_api/c_api_error.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/c_api/c_api_error.cc.s
.PHONY : src/c_api/c_api_error.cc.s

src/cli_main.o: src/cli_main.cc.o

.PHONY : src/cli_main.o

# target to build an object file
src/cli_main.cc.o:
	$(MAKE) -f CMakeFiles/runxgboost.dir/build.make CMakeFiles/runxgboost.dir/src/cli_main.cc.o
.PHONY : src/cli_main.cc.o

src/cli_main.i: src/cli_main.cc.i

.PHONY : src/cli_main.i

# target to preprocess a source file
src/cli_main.cc.i:
	$(MAKE) -f CMakeFiles/runxgboost.dir/build.make CMakeFiles/runxgboost.dir/src/cli_main.cc.i
.PHONY : src/cli_main.cc.i

src/cli_main.s: src/cli_main.cc.s

.PHONY : src/cli_main.s

# target to generate assembly for a file
src/cli_main.cc.s:
	$(MAKE) -f CMakeFiles/runxgboost.dir/build.make CMakeFiles/runxgboost.dir/src/cli_main.cc.s
.PHONY : src/cli_main.cc.s

src/common/common.o: src/common/common.cc.o

.PHONY : src/common/common.o

# target to build an object file
src/common/common.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/common.cc.o
.PHONY : src/common/common.cc.o

src/common/common.i: src/common/common.cc.i

.PHONY : src/common/common.i

# target to preprocess a source file
src/common/common.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/common.cc.i
.PHONY : src/common/common.cc.i

src/common/common.s: src/common/common.cc.s

.PHONY : src/common/common.s

# target to generate assembly for a file
src/common/common.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/common.cc.s
.PHONY : src/common/common.cc.s

src/common/hist_util.o: src/common/hist_util.cc.o

.PHONY : src/common/hist_util.o

# target to build an object file
src/common/hist_util.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/hist_util.cc.o
.PHONY : src/common/hist_util.cc.o

src/common/hist_util.i: src/common/hist_util.cc.i

.PHONY : src/common/hist_util.i

# target to preprocess a source file
src/common/hist_util.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/hist_util.cc.i
.PHONY : src/common/hist_util.cc.i

src/common/hist_util.s: src/common/hist_util.cc.s

.PHONY : src/common/hist_util.s

# target to generate assembly for a file
src/common/hist_util.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/hist_util.cc.s
.PHONY : src/common/hist_util.cc.s

src/common/host_device_vector.o: src/common/host_device_vector.cc.o

.PHONY : src/common/host_device_vector.o

# target to build an object file
src/common/host_device_vector.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/host_device_vector.cc.o
.PHONY : src/common/host_device_vector.cc.o

src/common/host_device_vector.i: src/common/host_device_vector.cc.i

.PHONY : src/common/host_device_vector.i

# target to preprocess a source file
src/common/host_device_vector.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/host_device_vector.cc.i
.PHONY : src/common/host_device_vector.cc.i

src/common/host_device_vector.s: src/common/host_device_vector.cc.s

.PHONY : src/common/host_device_vector.s

# target to generate assembly for a file
src/common/host_device_vector.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/common/host_device_vector.cc.s
.PHONY : src/common/host_device_vector.cc.s

src/data/data.o: src/data/data.cc.o

.PHONY : src/data/data.o

# target to build an object file
src/data/data.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/data.cc.o
.PHONY : src/data/data.cc.o

src/data/data.i: src/data/data.cc.i

.PHONY : src/data/data.i

# target to preprocess a source file
src/data/data.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/data.cc.i
.PHONY : src/data/data.cc.i

src/data/data.s: src/data/data.cc.s

.PHONY : src/data/data.s

# target to generate assembly for a file
src/data/data.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/data.cc.s
.PHONY : src/data/data.cc.s

src/data/simple_csr_source.o: src/data/simple_csr_source.cc.o

.PHONY : src/data/simple_csr_source.o

# target to build an object file
src/data/simple_csr_source.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/simple_csr_source.cc.o
.PHONY : src/data/simple_csr_source.cc.o

src/data/simple_csr_source.i: src/data/simple_csr_source.cc.i

.PHONY : src/data/simple_csr_source.i

# target to preprocess a source file
src/data/simple_csr_source.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/simple_csr_source.cc.i
.PHONY : src/data/simple_csr_source.cc.i

src/data/simple_csr_source.s: src/data/simple_csr_source.cc.s

.PHONY : src/data/simple_csr_source.s

# target to generate assembly for a file
src/data/simple_csr_source.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/simple_csr_source.cc.s
.PHONY : src/data/simple_csr_source.cc.s

src/data/simple_dmatrix.o: src/data/simple_dmatrix.cc.o

.PHONY : src/data/simple_dmatrix.o

# target to build an object file
src/data/simple_dmatrix.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/simple_dmatrix.cc.o
.PHONY : src/data/simple_dmatrix.cc.o

src/data/simple_dmatrix.i: src/data/simple_dmatrix.cc.i

.PHONY : src/data/simple_dmatrix.i

# target to preprocess a source file
src/data/simple_dmatrix.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/simple_dmatrix.cc.i
.PHONY : src/data/simple_dmatrix.cc.i

src/data/simple_dmatrix.s: src/data/simple_dmatrix.cc.s

.PHONY : src/data/simple_dmatrix.s

# target to generate assembly for a file
src/data/simple_dmatrix.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/simple_dmatrix.cc.s
.PHONY : src/data/simple_dmatrix.cc.s

src/data/sparse_page_dmatrix.o: src/data/sparse_page_dmatrix.cc.o

.PHONY : src/data/sparse_page_dmatrix.o

# target to build an object file
src/data/sparse_page_dmatrix.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_dmatrix.cc.o
.PHONY : src/data/sparse_page_dmatrix.cc.o

src/data/sparse_page_dmatrix.i: src/data/sparse_page_dmatrix.cc.i

.PHONY : src/data/sparse_page_dmatrix.i

# target to preprocess a source file
src/data/sparse_page_dmatrix.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_dmatrix.cc.i
.PHONY : src/data/sparse_page_dmatrix.cc.i

src/data/sparse_page_dmatrix.s: src/data/sparse_page_dmatrix.cc.s

.PHONY : src/data/sparse_page_dmatrix.s

# target to generate assembly for a file
src/data/sparse_page_dmatrix.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_dmatrix.cc.s
.PHONY : src/data/sparse_page_dmatrix.cc.s

src/data/sparse_page_raw_format.o: src/data/sparse_page_raw_format.cc.o

.PHONY : src/data/sparse_page_raw_format.o

# target to build an object file
src/data/sparse_page_raw_format.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_raw_format.cc.o
.PHONY : src/data/sparse_page_raw_format.cc.o

src/data/sparse_page_raw_format.i: src/data/sparse_page_raw_format.cc.i

.PHONY : src/data/sparse_page_raw_format.i

# target to preprocess a source file
src/data/sparse_page_raw_format.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_raw_format.cc.i
.PHONY : src/data/sparse_page_raw_format.cc.i

src/data/sparse_page_raw_format.s: src/data/sparse_page_raw_format.cc.s

.PHONY : src/data/sparse_page_raw_format.s

# target to generate assembly for a file
src/data/sparse_page_raw_format.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_raw_format.cc.s
.PHONY : src/data/sparse_page_raw_format.cc.s

src/data/sparse_page_source.o: src/data/sparse_page_source.cc.o

.PHONY : src/data/sparse_page_source.o

# target to build an object file
src/data/sparse_page_source.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_source.cc.o
.PHONY : src/data/sparse_page_source.cc.o

src/data/sparse_page_source.i: src/data/sparse_page_source.cc.i

.PHONY : src/data/sparse_page_source.i

# target to preprocess a source file
src/data/sparse_page_source.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_source.cc.i
.PHONY : src/data/sparse_page_source.cc.i

src/data/sparse_page_source.s: src/data/sparse_page_source.cc.s

.PHONY : src/data/sparse_page_source.s

# target to generate assembly for a file
src/data/sparse_page_source.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_source.cc.s
.PHONY : src/data/sparse_page_source.cc.s

src/data/sparse_page_writer.o: src/data/sparse_page_writer.cc.o

.PHONY : src/data/sparse_page_writer.o

# target to build an object file
src/data/sparse_page_writer.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_writer.cc.o
.PHONY : src/data/sparse_page_writer.cc.o

src/data/sparse_page_writer.i: src/data/sparse_page_writer.cc.i

.PHONY : src/data/sparse_page_writer.i

# target to preprocess a source file
src/data/sparse_page_writer.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_writer.cc.i
.PHONY : src/data/sparse_page_writer.cc.i

src/data/sparse_page_writer.s: src/data/sparse_page_writer.cc.s

.PHONY : src/data/sparse_page_writer.s

# target to generate assembly for a file
src/data/sparse_page_writer.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/data/sparse_page_writer.cc.s
.PHONY : src/data/sparse_page_writer.cc.s

src/gbm/gblinear.o: src/gbm/gblinear.cc.o

.PHONY : src/gbm/gblinear.o

# target to build an object file
src/gbm/gblinear.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gblinear.cc.o
.PHONY : src/gbm/gblinear.cc.o

src/gbm/gblinear.i: src/gbm/gblinear.cc.i

.PHONY : src/gbm/gblinear.i

# target to preprocess a source file
src/gbm/gblinear.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gblinear.cc.i
.PHONY : src/gbm/gblinear.cc.i

src/gbm/gblinear.s: src/gbm/gblinear.cc.s

.PHONY : src/gbm/gblinear.s

# target to generate assembly for a file
src/gbm/gblinear.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gblinear.cc.s
.PHONY : src/gbm/gblinear.cc.s

src/gbm/gbm.o: src/gbm/gbm.cc.o

.PHONY : src/gbm/gbm.o

# target to build an object file
src/gbm/gbm.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gbm.cc.o
.PHONY : src/gbm/gbm.cc.o

src/gbm/gbm.i: src/gbm/gbm.cc.i

.PHONY : src/gbm/gbm.i

# target to preprocess a source file
src/gbm/gbm.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gbm.cc.i
.PHONY : src/gbm/gbm.cc.i

src/gbm/gbm.s: src/gbm/gbm.cc.s

.PHONY : src/gbm/gbm.s

# target to generate assembly for a file
src/gbm/gbm.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gbm.cc.s
.PHONY : src/gbm/gbm.cc.s

src/gbm/gbtree.o: src/gbm/gbtree.cc.o

.PHONY : src/gbm/gbtree.o

# target to build an object file
src/gbm/gbtree.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gbtree.cc.o
.PHONY : src/gbm/gbtree.cc.o

src/gbm/gbtree.i: src/gbm/gbtree.cc.i

.PHONY : src/gbm/gbtree.i

# target to preprocess a source file
src/gbm/gbtree.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gbtree.cc.i
.PHONY : src/gbm/gbtree.cc.i

src/gbm/gbtree.s: src/gbm/gbtree.cc.s

.PHONY : src/gbm/gbtree.s

# target to generate assembly for a file
src/gbm/gbtree.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/gbm/gbtree.cc.s
.PHONY : src/gbm/gbtree.cc.s

src/learner.o: src/learner.cc.o

.PHONY : src/learner.o

# target to build an object file
src/learner.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/learner.cc.o
.PHONY : src/learner.cc.o

src/learner.i: src/learner.cc.i

.PHONY : src/learner.i

# target to preprocess a source file
src/learner.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/learner.cc.i
.PHONY : src/learner.cc.i

src/learner.s: src/learner.cc.s

.PHONY : src/learner.s

# target to generate assembly for a file
src/learner.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/learner.cc.s
.PHONY : src/learner.cc.s

src/linear/linear_updater.o: src/linear/linear_updater.cc.o

.PHONY : src/linear/linear_updater.o

# target to build an object file
src/linear/linear_updater.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/linear_updater.cc.o
.PHONY : src/linear/linear_updater.cc.o

src/linear/linear_updater.i: src/linear/linear_updater.cc.i

.PHONY : src/linear/linear_updater.i

# target to preprocess a source file
src/linear/linear_updater.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/linear_updater.cc.i
.PHONY : src/linear/linear_updater.cc.i

src/linear/linear_updater.s: src/linear/linear_updater.cc.s

.PHONY : src/linear/linear_updater.s

# target to generate assembly for a file
src/linear/linear_updater.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/linear_updater.cc.s
.PHONY : src/linear/linear_updater.cc.s

src/linear/updater_coordinate.o: src/linear/updater_coordinate.cc.o

.PHONY : src/linear/updater_coordinate.o

# target to build an object file
src/linear/updater_coordinate.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/updater_coordinate.cc.o
.PHONY : src/linear/updater_coordinate.cc.o

src/linear/updater_coordinate.i: src/linear/updater_coordinate.cc.i

.PHONY : src/linear/updater_coordinate.i

# target to preprocess a source file
src/linear/updater_coordinate.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/updater_coordinate.cc.i
.PHONY : src/linear/updater_coordinate.cc.i

src/linear/updater_coordinate.s: src/linear/updater_coordinate.cc.s

.PHONY : src/linear/updater_coordinate.s

# target to generate assembly for a file
src/linear/updater_coordinate.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/updater_coordinate.cc.s
.PHONY : src/linear/updater_coordinate.cc.s

src/linear/updater_shotgun.o: src/linear/updater_shotgun.cc.o

.PHONY : src/linear/updater_shotgun.o

# target to build an object file
src/linear/updater_shotgun.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/updater_shotgun.cc.o
.PHONY : src/linear/updater_shotgun.cc.o

src/linear/updater_shotgun.i: src/linear/updater_shotgun.cc.i

.PHONY : src/linear/updater_shotgun.i

# target to preprocess a source file
src/linear/updater_shotgun.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/updater_shotgun.cc.i
.PHONY : src/linear/updater_shotgun.cc.i

src/linear/updater_shotgun.s: src/linear/updater_shotgun.cc.s

.PHONY : src/linear/updater_shotgun.s

# target to generate assembly for a file
src/linear/updater_shotgun.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/linear/updater_shotgun.cc.s
.PHONY : src/linear/updater_shotgun.cc.s

src/logging.o: src/logging.cc.o

.PHONY : src/logging.o

# target to build an object file
src/logging.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/logging.cc.o
.PHONY : src/logging.cc.o

src/logging.i: src/logging.cc.i

.PHONY : src/logging.i

# target to preprocess a source file
src/logging.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/logging.cc.i
.PHONY : src/logging.cc.i

src/logging.s: src/logging.cc.s

.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/logging.cc.s
.PHONY : src/logging.cc.s

src/metric/elementwise_metric.o: src/metric/elementwise_metric.cc.o

.PHONY : src/metric/elementwise_metric.o

# target to build an object file
src/metric/elementwise_metric.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/elementwise_metric.cc.o
.PHONY : src/metric/elementwise_metric.cc.o

src/metric/elementwise_metric.i: src/metric/elementwise_metric.cc.i

.PHONY : src/metric/elementwise_metric.i

# target to preprocess a source file
src/metric/elementwise_metric.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/elementwise_metric.cc.i
.PHONY : src/metric/elementwise_metric.cc.i

src/metric/elementwise_metric.s: src/metric/elementwise_metric.cc.s

.PHONY : src/metric/elementwise_metric.s

# target to generate assembly for a file
src/metric/elementwise_metric.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/elementwise_metric.cc.s
.PHONY : src/metric/elementwise_metric.cc.s

src/metric/metric.o: src/metric/metric.cc.o

.PHONY : src/metric/metric.o

# target to build an object file
src/metric/metric.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/metric.cc.o
.PHONY : src/metric/metric.cc.o

src/metric/metric.i: src/metric/metric.cc.i

.PHONY : src/metric/metric.i

# target to preprocess a source file
src/metric/metric.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/metric.cc.i
.PHONY : src/metric/metric.cc.i

src/metric/metric.s: src/metric/metric.cc.s

.PHONY : src/metric/metric.s

# target to generate assembly for a file
src/metric/metric.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/metric.cc.s
.PHONY : src/metric/metric.cc.s

src/metric/multiclass_metric.o: src/metric/multiclass_metric.cc.o

.PHONY : src/metric/multiclass_metric.o

# target to build an object file
src/metric/multiclass_metric.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/multiclass_metric.cc.o
.PHONY : src/metric/multiclass_metric.cc.o

src/metric/multiclass_metric.i: src/metric/multiclass_metric.cc.i

.PHONY : src/metric/multiclass_metric.i

# target to preprocess a source file
src/metric/multiclass_metric.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/multiclass_metric.cc.i
.PHONY : src/metric/multiclass_metric.cc.i

src/metric/multiclass_metric.s: src/metric/multiclass_metric.cc.s

.PHONY : src/metric/multiclass_metric.s

# target to generate assembly for a file
src/metric/multiclass_metric.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/multiclass_metric.cc.s
.PHONY : src/metric/multiclass_metric.cc.s

src/metric/rank_metric.o: src/metric/rank_metric.cc.o

.PHONY : src/metric/rank_metric.o

# target to build an object file
src/metric/rank_metric.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/rank_metric.cc.o
.PHONY : src/metric/rank_metric.cc.o

src/metric/rank_metric.i: src/metric/rank_metric.cc.i

.PHONY : src/metric/rank_metric.i

# target to preprocess a source file
src/metric/rank_metric.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/rank_metric.cc.i
.PHONY : src/metric/rank_metric.cc.i

src/metric/rank_metric.s: src/metric/rank_metric.cc.s

.PHONY : src/metric/rank_metric.s

# target to generate assembly for a file
src/metric/rank_metric.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/metric/rank_metric.cc.s
.PHONY : src/metric/rank_metric.cc.s

src/objective/hinge.o: src/objective/hinge.cc.o

.PHONY : src/objective/hinge.o

# target to build an object file
src/objective/hinge.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/hinge.cc.o
.PHONY : src/objective/hinge.cc.o

src/objective/hinge.i: src/objective/hinge.cc.i

.PHONY : src/objective/hinge.i

# target to preprocess a source file
src/objective/hinge.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/hinge.cc.i
.PHONY : src/objective/hinge.cc.i

src/objective/hinge.s: src/objective/hinge.cc.s

.PHONY : src/objective/hinge.s

# target to generate assembly for a file
src/objective/hinge.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/hinge.cc.s
.PHONY : src/objective/hinge.cc.s

src/objective/multiclass_obj.o: src/objective/multiclass_obj.cc.o

.PHONY : src/objective/multiclass_obj.o

# target to build an object file
src/objective/multiclass_obj.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/multiclass_obj.cc.o
.PHONY : src/objective/multiclass_obj.cc.o

src/objective/multiclass_obj.i: src/objective/multiclass_obj.cc.i

.PHONY : src/objective/multiclass_obj.i

# target to preprocess a source file
src/objective/multiclass_obj.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/multiclass_obj.cc.i
.PHONY : src/objective/multiclass_obj.cc.i

src/objective/multiclass_obj.s: src/objective/multiclass_obj.cc.s

.PHONY : src/objective/multiclass_obj.s

# target to generate assembly for a file
src/objective/multiclass_obj.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/multiclass_obj.cc.s
.PHONY : src/objective/multiclass_obj.cc.s

src/objective/objective.o: src/objective/objective.cc.o

.PHONY : src/objective/objective.o

# target to build an object file
src/objective/objective.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/objective.cc.o
.PHONY : src/objective/objective.cc.o

src/objective/objective.i: src/objective/objective.cc.i

.PHONY : src/objective/objective.i

# target to preprocess a source file
src/objective/objective.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/objective.cc.i
.PHONY : src/objective/objective.cc.i

src/objective/objective.s: src/objective/objective.cc.s

.PHONY : src/objective/objective.s

# target to generate assembly for a file
src/objective/objective.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/objective.cc.s
.PHONY : src/objective/objective.cc.s

src/objective/rank_obj.o: src/objective/rank_obj.cc.o

.PHONY : src/objective/rank_obj.o

# target to build an object file
src/objective/rank_obj.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/rank_obj.cc.o
.PHONY : src/objective/rank_obj.cc.o

src/objective/rank_obj.i: src/objective/rank_obj.cc.i

.PHONY : src/objective/rank_obj.i

# target to preprocess a source file
src/objective/rank_obj.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/rank_obj.cc.i
.PHONY : src/objective/rank_obj.cc.i

src/objective/rank_obj.s: src/objective/rank_obj.cc.s

.PHONY : src/objective/rank_obj.s

# target to generate assembly for a file
src/objective/rank_obj.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/rank_obj.cc.s
.PHONY : src/objective/rank_obj.cc.s

src/objective/regression_obj.o: src/objective/regression_obj.cc.o

.PHONY : src/objective/regression_obj.o

# target to build an object file
src/objective/regression_obj.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/regression_obj.cc.o
.PHONY : src/objective/regression_obj.cc.o

src/objective/regression_obj.i: src/objective/regression_obj.cc.i

.PHONY : src/objective/regression_obj.i

# target to preprocess a source file
src/objective/regression_obj.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/regression_obj.cc.i
.PHONY : src/objective/regression_obj.cc.i

src/objective/regression_obj.s: src/objective/regression_obj.cc.s

.PHONY : src/objective/regression_obj.s

# target to generate assembly for a file
src/objective/regression_obj.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/objective/regression_obj.cc.s
.PHONY : src/objective/regression_obj.cc.s

src/predictor/cpu_predictor.o: src/predictor/cpu_predictor.cc.o

.PHONY : src/predictor/cpu_predictor.o

# target to build an object file
src/predictor/cpu_predictor.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/predictor/cpu_predictor.cc.o
.PHONY : src/predictor/cpu_predictor.cc.o

src/predictor/cpu_predictor.i: src/predictor/cpu_predictor.cc.i

.PHONY : src/predictor/cpu_predictor.i

# target to preprocess a source file
src/predictor/cpu_predictor.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/predictor/cpu_predictor.cc.i
.PHONY : src/predictor/cpu_predictor.cc.i

src/predictor/cpu_predictor.s: src/predictor/cpu_predictor.cc.s

.PHONY : src/predictor/cpu_predictor.s

# target to generate assembly for a file
src/predictor/cpu_predictor.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/predictor/cpu_predictor.cc.s
.PHONY : src/predictor/cpu_predictor.cc.s

src/predictor/predictor.o: src/predictor/predictor.cc.o

.PHONY : src/predictor/predictor.o

# target to build an object file
src/predictor/predictor.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/predictor/predictor.cc.o
.PHONY : src/predictor/predictor.cc.o

src/predictor/predictor.i: src/predictor/predictor.cc.i

.PHONY : src/predictor/predictor.i

# target to preprocess a source file
src/predictor/predictor.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/predictor/predictor.cc.i
.PHONY : src/predictor/predictor.cc.i

src/predictor/predictor.s: src/predictor/predictor.cc.s

.PHONY : src/predictor/predictor.s

# target to generate assembly for a file
src/predictor/predictor.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/predictor/predictor.cc.s
.PHONY : src/predictor/predictor.cc.s

src/tree/split_evaluator.o: src/tree/split_evaluator.cc.o

.PHONY : src/tree/split_evaluator.o

# target to build an object file
src/tree/split_evaluator.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/split_evaluator.cc.o
.PHONY : src/tree/split_evaluator.cc.o

src/tree/split_evaluator.i: src/tree/split_evaluator.cc.i

.PHONY : src/tree/split_evaluator.i

# target to preprocess a source file
src/tree/split_evaluator.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/split_evaluator.cc.i
.PHONY : src/tree/split_evaluator.cc.i

src/tree/split_evaluator.s: src/tree/split_evaluator.cc.s

.PHONY : src/tree/split_evaluator.s

# target to generate assembly for a file
src/tree/split_evaluator.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/split_evaluator.cc.s
.PHONY : src/tree/split_evaluator.cc.s

src/tree/tree_model.o: src/tree/tree_model.cc.o

.PHONY : src/tree/tree_model.o

# target to build an object file
src/tree/tree_model.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/tree_model.cc.o
.PHONY : src/tree/tree_model.cc.o

src/tree/tree_model.i: src/tree/tree_model.cc.i

.PHONY : src/tree/tree_model.i

# target to preprocess a source file
src/tree/tree_model.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/tree_model.cc.i
.PHONY : src/tree/tree_model.cc.i

src/tree/tree_model.s: src/tree/tree_model.cc.s

.PHONY : src/tree/tree_model.s

# target to generate assembly for a file
src/tree/tree_model.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/tree_model.cc.s
.PHONY : src/tree/tree_model.cc.s

src/tree/tree_updater.o: src/tree/tree_updater.cc.o

.PHONY : src/tree/tree_updater.o

# target to build an object file
src/tree/tree_updater.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/tree_updater.cc.o
.PHONY : src/tree/tree_updater.cc.o

src/tree/tree_updater.i: src/tree/tree_updater.cc.i

.PHONY : src/tree/tree_updater.i

# target to preprocess a source file
src/tree/tree_updater.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/tree_updater.cc.i
.PHONY : src/tree/tree_updater.cc.i

src/tree/tree_updater.s: src/tree/tree_updater.cc.s

.PHONY : src/tree/tree_updater.s

# target to generate assembly for a file
src/tree/tree_updater.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/tree_updater.cc.s
.PHONY : src/tree/tree_updater.cc.s

src/tree/updater_colmaker.o: src/tree/updater_colmaker.cc.o

.PHONY : src/tree/updater_colmaker.o

# target to build an object file
src/tree/updater_colmaker.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_colmaker.cc.o
.PHONY : src/tree/updater_colmaker.cc.o

src/tree/updater_colmaker.i: src/tree/updater_colmaker.cc.i

.PHONY : src/tree/updater_colmaker.i

# target to preprocess a source file
src/tree/updater_colmaker.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_colmaker.cc.i
.PHONY : src/tree/updater_colmaker.cc.i

src/tree/updater_colmaker.s: src/tree/updater_colmaker.cc.s

.PHONY : src/tree/updater_colmaker.s

# target to generate assembly for a file
src/tree/updater_colmaker.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_colmaker.cc.s
.PHONY : src/tree/updater_colmaker.cc.s

src/tree/updater_histmaker.o: src/tree/updater_histmaker.cc.o

.PHONY : src/tree/updater_histmaker.o

# target to build an object file
src/tree/updater_histmaker.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_histmaker.cc.o
.PHONY : src/tree/updater_histmaker.cc.o

src/tree/updater_histmaker.i: src/tree/updater_histmaker.cc.i

.PHONY : src/tree/updater_histmaker.i

# target to preprocess a source file
src/tree/updater_histmaker.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_histmaker.cc.i
.PHONY : src/tree/updater_histmaker.cc.i

src/tree/updater_histmaker.s: src/tree/updater_histmaker.cc.s

.PHONY : src/tree/updater_histmaker.s

# target to generate assembly for a file
src/tree/updater_histmaker.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_histmaker.cc.s
.PHONY : src/tree/updater_histmaker.cc.s

src/tree/updater_prune.o: src/tree/updater_prune.cc.o

.PHONY : src/tree/updater_prune.o

# target to build an object file
src/tree/updater_prune.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_prune.cc.o
.PHONY : src/tree/updater_prune.cc.o

src/tree/updater_prune.i: src/tree/updater_prune.cc.i

.PHONY : src/tree/updater_prune.i

# target to preprocess a source file
src/tree/updater_prune.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_prune.cc.i
.PHONY : src/tree/updater_prune.cc.i

src/tree/updater_prune.s: src/tree/updater_prune.cc.s

.PHONY : src/tree/updater_prune.s

# target to generate assembly for a file
src/tree/updater_prune.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_prune.cc.s
.PHONY : src/tree/updater_prune.cc.s

src/tree/updater_quantile_hist.o: src/tree/updater_quantile_hist.cc.o

.PHONY : src/tree/updater_quantile_hist.o

# target to build an object file
src/tree/updater_quantile_hist.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_quantile_hist.cc.o
.PHONY : src/tree/updater_quantile_hist.cc.o

src/tree/updater_quantile_hist.i: src/tree/updater_quantile_hist.cc.i

.PHONY : src/tree/updater_quantile_hist.i

# target to preprocess a source file
src/tree/updater_quantile_hist.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_quantile_hist.cc.i
.PHONY : src/tree/updater_quantile_hist.cc.i

src/tree/updater_quantile_hist.s: src/tree/updater_quantile_hist.cc.s

.PHONY : src/tree/updater_quantile_hist.s

# target to generate assembly for a file
src/tree/updater_quantile_hist.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_quantile_hist.cc.s
.PHONY : src/tree/updater_quantile_hist.cc.s

src/tree/updater_refresh.o: src/tree/updater_refresh.cc.o

.PHONY : src/tree/updater_refresh.o

# target to build an object file
src/tree/updater_refresh.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_refresh.cc.o
.PHONY : src/tree/updater_refresh.cc.o

src/tree/updater_refresh.i: src/tree/updater_refresh.cc.i

.PHONY : src/tree/updater_refresh.i

# target to preprocess a source file
src/tree/updater_refresh.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_refresh.cc.i
.PHONY : src/tree/updater_refresh.cc.i

src/tree/updater_refresh.s: src/tree/updater_refresh.cc.s

.PHONY : src/tree/updater_refresh.s

# target to generate assembly for a file
src/tree/updater_refresh.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_refresh.cc.s
.PHONY : src/tree/updater_refresh.cc.s

src/tree/updater_skmaker.o: src/tree/updater_skmaker.cc.o

.PHONY : src/tree/updater_skmaker.o

# target to build an object file
src/tree/updater_skmaker.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_skmaker.cc.o
.PHONY : src/tree/updater_skmaker.cc.o

src/tree/updater_skmaker.i: src/tree/updater_skmaker.cc.i

.PHONY : src/tree/updater_skmaker.i

# target to preprocess a source file
src/tree/updater_skmaker.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_skmaker.cc.i
.PHONY : src/tree/updater_skmaker.cc.i

src/tree/updater_skmaker.s: src/tree/updater_skmaker.cc.s

.PHONY : src/tree/updater_skmaker.s

# target to generate assembly for a file
src/tree/updater_skmaker.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_skmaker.cc.s
.PHONY : src/tree/updater_skmaker.cc.s

src/tree/updater_sync.o: src/tree/updater_sync.cc.o

.PHONY : src/tree/updater_sync.o

# target to build an object file
src/tree/updater_sync.cc.o:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_sync.cc.o
.PHONY : src/tree/updater_sync.cc.o

src/tree/updater_sync.i: src/tree/updater_sync.cc.i

.PHONY : src/tree/updater_sync.i

# target to preprocess a source file
src/tree/updater_sync.cc.i:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_sync.cc.i
.PHONY : src/tree/updater_sync.cc.i

src/tree/updater_sync.s: src/tree/updater_sync.cc.s

.PHONY : src/tree/updater_sync.s

# target to generate assembly for a file
src/tree/updater_sync.cc.s:
	$(MAKE) -f CMakeFiles/objxgboost.dir/build.make CMakeFiles/objxgboost.dir/src/tree/updater_sync.cc.s
.PHONY : src/tree/updater_sync.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... rabit"
	@echo "... objxgboost"
	@echo "... xgboost"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... runxgboost"
	@echo "... dmlc"
	@echo "... dmlc_lint"
	@echo "... rabit/src/allreduce_base.o"
	@echo "... rabit/src/allreduce_base.i"
	@echo "... rabit/src/allreduce_base.s"
	@echo "... rabit/src/allreduce_robust.o"
	@echo "... rabit/src/allreduce_robust.i"
	@echo "... rabit/src/allreduce_robust.s"
	@echo "... rabit/src/c_api.o"
	@echo "... rabit/src/c_api.i"
	@echo "... rabit/src/c_api.s"
	@echo "... rabit/src/engine.o"
	@echo "... rabit/src/engine.i"
	@echo "... rabit/src/engine.s"
	@echo "... src/c_api/c_api.o"
	@echo "... src/c_api/c_api.i"
	@echo "... src/c_api/c_api.s"
	@echo "... src/c_api/c_api_error.o"
	@echo "... src/c_api/c_api_error.i"
	@echo "... src/c_api/c_api_error.s"
	@echo "... src/cli_main.o"
	@echo "... src/cli_main.i"
	@echo "... src/cli_main.s"
	@echo "... src/common/common.o"
	@echo "... src/common/common.i"
	@echo "... src/common/common.s"
	@echo "... src/common/hist_util.o"
	@echo "... src/common/hist_util.i"
	@echo "... src/common/hist_util.s"
	@echo "... src/common/host_device_vector.o"
	@echo "... src/common/host_device_vector.i"
	@echo "... src/common/host_device_vector.s"
	@echo "... src/data/data.o"
	@echo "... src/data/data.i"
	@echo "... src/data/data.s"
	@echo "... src/data/simple_csr_source.o"
	@echo "... src/data/simple_csr_source.i"
	@echo "... src/data/simple_csr_source.s"
	@echo "... src/data/simple_dmatrix.o"
	@echo "... src/data/simple_dmatrix.i"
	@echo "... src/data/simple_dmatrix.s"
	@echo "... src/data/sparse_page_dmatrix.o"
	@echo "... src/data/sparse_page_dmatrix.i"
	@echo "... src/data/sparse_page_dmatrix.s"
	@echo "... src/data/sparse_page_raw_format.o"
	@echo "... src/data/sparse_page_raw_format.i"
	@echo "... src/data/sparse_page_raw_format.s"
	@echo "... src/data/sparse_page_source.o"
	@echo "... src/data/sparse_page_source.i"
	@echo "... src/data/sparse_page_source.s"
	@echo "... src/data/sparse_page_writer.o"
	@echo "... src/data/sparse_page_writer.i"
	@echo "... src/data/sparse_page_writer.s"
	@echo "... src/gbm/gblinear.o"
	@echo "... src/gbm/gblinear.i"
	@echo "... src/gbm/gblinear.s"
	@echo "... src/gbm/gbm.o"
	@echo "... src/gbm/gbm.i"
	@echo "... src/gbm/gbm.s"
	@echo "... src/gbm/gbtree.o"
	@echo "... src/gbm/gbtree.i"
	@echo "... src/gbm/gbtree.s"
	@echo "... src/learner.o"
	@echo "... src/learner.i"
	@echo "... src/learner.s"
	@echo "... src/linear/linear_updater.o"
	@echo "... src/linear/linear_updater.i"
	@echo "... src/linear/linear_updater.s"
	@echo "... src/linear/updater_coordinate.o"
	@echo "... src/linear/updater_coordinate.i"
	@echo "... src/linear/updater_coordinate.s"
	@echo "... src/linear/updater_shotgun.o"
	@echo "... src/linear/updater_shotgun.i"
	@echo "... src/linear/updater_shotgun.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... src/metric/elementwise_metric.o"
	@echo "... src/metric/elementwise_metric.i"
	@echo "... src/metric/elementwise_metric.s"
	@echo "... src/metric/metric.o"
	@echo "... src/metric/metric.i"
	@echo "... src/metric/metric.s"
	@echo "... src/metric/multiclass_metric.o"
	@echo "... src/metric/multiclass_metric.i"
	@echo "... src/metric/multiclass_metric.s"
	@echo "... src/metric/rank_metric.o"
	@echo "... src/metric/rank_metric.i"
	@echo "... src/metric/rank_metric.s"
	@echo "... src/objective/hinge.o"
	@echo "... src/objective/hinge.i"
	@echo "... src/objective/hinge.s"
	@echo "... src/objective/multiclass_obj.o"
	@echo "... src/objective/multiclass_obj.i"
	@echo "... src/objective/multiclass_obj.s"
	@echo "... src/objective/objective.o"
	@echo "... src/objective/objective.i"
	@echo "... src/objective/objective.s"
	@echo "... src/objective/rank_obj.o"
	@echo "... src/objective/rank_obj.i"
	@echo "... src/objective/rank_obj.s"
	@echo "... src/objective/regression_obj.o"
	@echo "... src/objective/regression_obj.i"
	@echo "... src/objective/regression_obj.s"
	@echo "... src/predictor/cpu_predictor.o"
	@echo "... src/predictor/cpu_predictor.i"
	@echo "... src/predictor/cpu_predictor.s"
	@echo "... src/predictor/predictor.o"
	@echo "... src/predictor/predictor.i"
	@echo "... src/predictor/predictor.s"
	@echo "... src/tree/split_evaluator.o"
	@echo "... src/tree/split_evaluator.i"
	@echo "... src/tree/split_evaluator.s"
	@echo "... src/tree/tree_model.o"
	@echo "... src/tree/tree_model.i"
	@echo "... src/tree/tree_model.s"
	@echo "... src/tree/tree_updater.o"
	@echo "... src/tree/tree_updater.i"
	@echo "... src/tree/tree_updater.s"
	@echo "... src/tree/updater_colmaker.o"
	@echo "... src/tree/updater_colmaker.i"
	@echo "... src/tree/updater_colmaker.s"
	@echo "... src/tree/updater_histmaker.o"
	@echo "... src/tree/updater_histmaker.i"
	@echo "... src/tree/updater_histmaker.s"
	@echo "... src/tree/updater_prune.o"
	@echo "... src/tree/updater_prune.i"
	@echo "... src/tree/updater_prune.s"
	@echo "... src/tree/updater_quantile_hist.o"
	@echo "... src/tree/updater_quantile_hist.i"
	@echo "... src/tree/updater_quantile_hist.s"
	@echo "... src/tree/updater_refresh.o"
	@echo "... src/tree/updater_refresh.i"
	@echo "... src/tree/updater_refresh.s"
	@echo "... src/tree/updater_skmaker.o"
	@echo "... src/tree/updater_skmaker.i"
	@echo "... src/tree/updater_skmaker.s"
	@echo "... src/tree/updater_sync.o"
	@echo "... src/tree/updater_sync.i"
	@echo "... src/tree/updater_sync.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

